### ISSUE TITLE
Bug in protocol() method

### ISSUE THREAD

**Issue by targos** [poppinss/request#8]
If `trustProxy` returns false, the `protocol()` method always returns `null`.

The reason is that the following line actually will never return a string, because IncomingMessage.url doesn't contain information about the protocol/hostname/port. [It only has the path part](https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_message_url)
https://github.com/poppinss/request/blob/9eaac0f55997db980c9254ce1fe6e4de84bb1722/src/Request.ts#L416

Here's a test case showing the issue:
```diff
diff --git a/test/request.spec.ts b/test/request.spec.ts
index cce62c0..4f6b22b 100644
--- a/test/request.spec.ts
+++ b/test/request.spec.ts
@@ -299,6 +299,22 @@ test.group('Request', () => {
     })
   })

+  test('get request protocol without trusting proxy', async (assert) => {
+    const server = createServer((req, res) => {
+      const config = fakeConfig()
+      config.trustProxy = () => false
+      const request = new Request(req, res, config)
+
+        res.writeHead(200, { 'content-type': 'application/json' })
+        res.end(JSON.stringify({ protocol: request.protocol() }))
+      })
+
+      const { body } = await supertest(server).get('/')
+      assert.deepEqual(body, {
+        protocol: 'http',
+      })
+  })
+
   test('get boolean telling request is secure or not', async (assert) => {
     const server = createServer((req, res) => {
       const request = new Request(req, res, fakeConfig())
```

```
Request

  ✖ get request protocol without trusting proxy
    Assertion Error: expected { protocol: null } to deeply equal { protocol: 'http' }
    {
      protocol: null => "http"
    }
```

**Comment by thetutlage** [comment]
Yup, makes sense that we should return `http` as a fallback. Mind sharing a PR for same?

Also, in future, you can do a PR with `test.failing` syntax. More about it [here](https://github.com/thetutlage/japa#regression-tests).

**Comment by targos** [comment]
I opened https://github.com/poppinss/request/pull/9
